"""add column decription2 into product

Revision ID: c9ce0bd2c9a0
Revises: 6cc6402a5ec9
Create Date: 2021-01-22 14:46:42.543246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ce0bd2c9a0'
down_revision = '6cc6402a5ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description2', sa.String(), nullable=True))
    op.create_index(op.f('ix_product_description2'), 'product', ['description2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_description2'), table_name='product')
    op.drop_column('product', 'description2')
    # ### end Alembic commands ###
